---
title: '17.4'
author: "Nikhil Gopal"
date: "2/27/2022"
output:
  html_document:
    df_print: paged
---

```{r, message=FALSE}
rm(list = ls())
```

**17.4**

Bias in deterministic imputation: Suppose you are imputing missing responses for income in
a social survey of American households, using for the imputation a regression model given
demographic variables. Which of the following two statements is basically true?


If you impute income deterministically using a fitted regression model (that is, imputing
using X β rather than X β + epsilon), you will tend to impute too many people as rich or poor: A
deterministic procedure overstates your certainty, making you more likely to impute extreme
values.


If you impute income deterministically using a fitted regression model (that is, imputing
using X β rather than X β + epsilon), you will tend to impute too many people as middle class: By
not using the error term, you’ll impute too many values in the middle of the distribution.



**Answer**

Statement a (the top one) is true. Deterministic imputation using regression will replace missing data with predicted values, and without a proper distribution of the error from the missing values, will tend to over or underestimate correlations between predictors and outcomes.