---
title: "Homework 02/28"
author: "Kerem Tuncer"
output: html_notebook
---
## Question 17.1

```{r}
rm(list = ls())
library(dplyr)
library(tidyr)
library(rstanarm)
data <- read.csv("https://raw.githubusercontent.com/avehtari/ROS-Examples/master/Earnings/data/earnings.csv")
data <- data[,c('weight','height','male')] %>% drop_na()

```

### Part A

(i)

```{r}
set.seed(1907)
fit <- stan_glm(weight ~ height+factor(male) , data = data, refresh=0)

print(fit)
```

(ii) 

```{r}
p_male <- 1 - 0.52
pop1 <- data.frame(male = c(0, 1), N = c(1 - p_male, p_male))
pop2 <- NULL
cut <- c(0, seq(50, 80, 1), 999)
for (i in 1:(length(cut)-1)){
   # male height distribution in the population  
   m_h <- pnorm(cut[i + 1], 69.1, 2.9) -  pnorm(cut[i], 69.1, 2.9)
   # female height distribution 
   f_h <- pnorm(cut[i + 1], 63.7, 2.7) -  pnorm(cut[i], 63.7, 2.7)
   pop2 <- bind_rows(pop2, 
                     data.frame(height = cut[i], male = 1, N = m_h),
                     data.frame(height = cut[i], male = 0, N = f_h))
}

pop2$N <- ifelse(pop2$male == 1, p_male * pop2$N, (1 - p_male) * pop2$N) 
```

```{r}
pred2 <- posterior_epred(fit, newdata = pop2)
```

(iii)

```{r}
poststrat2 <- pred2 %*% pop2$N 
median(poststrat2)
mad(poststrat2)
```

### Part B
(i)

```{r}
set.seed(1907)
fit <- stan_glm(weight ~ height+factor(male)+ height:factor(male), data = data, refresh=0)

print(fit)
```

(ii) 

```{r}
p_male <- 1 - 0.52
pop1 <- data.frame(male = c(0, 1), N = c(1 - p_male, p_male))
pop2 <- NULL
cut <- c(0, seq(50, 80, 1), 999)
for (i in 1:(length(cut)-1)){
   # male height distribution in the population  
   m_h <- pnorm(cut[i + 1], 69.1, 2.9) -  pnorm(cut[i], 69.1, 2.9)
   # female height distribution 
   f_h <- pnorm(cut[i + 1], 63.7, 2.7) -  pnorm(cut[i], 63.7, 2.7)
   pop2 <- bind_rows(pop2, 
                     data.frame(height = cut[i], male = 1, N = m_h),
                     data.frame(height = cut[i], male = 0, N = f_h))
}

pop2$N <- ifelse(pop2$male == 1, p_male * pop2$N, (1 - p_male) * pop2$N) 
```

```{r}
pred2 <- posterior_epred(fit, newdata = pop2)
```

(iii)

```{r}
poststrat2 <- pred2 %*% pop2$N 
median(poststrat2)
mad(poststrat2)
```

### Part C

(i)

```{r}
set.seed(1907)
fit <- stan_glm(log(weight) ~ height+factor(male), data = data, refresh=0)

print(fit)
```

(ii) 

```{r}
p_male <- 1 - 0.52
pop1 <- data.frame(male = c(0, 1), N = c(1 - p_male, p_male))
pop2 <- NULL
cut <- c(0, seq(50, 80, 1), 999)
for (i in 1:(length(cut)-1)){
   # male height distribution in the population  
   m_h <- pnorm(cut[i + 1], 69.1, 2.9) -  pnorm(cut[i], 69.1, 2.9)
   # female height distribution 
   f_h <- pnorm(cut[i + 1], 63.7, 2.7) -  pnorm(cut[i], 63.7, 2.7)
   pop2 <- bind_rows(pop2, 
                     data.frame(height = cut[i], male = 1, N = m_h),
                     data.frame(height = cut[i], male = 0, N = f_h))
}

pop2$N <- ifelse(pop2$male == 1, p_male * pop2$N, (1 - p_male) * pop2$N) 
```

```{r}
pred2 <- exp(posterior_epred(fit, newdata = pop2))
```

(iii)

```{r}
poststrat2 <- pred2 %*% pop2$N 
median(poststrat2)
mad(poststrat2)
```


(i)

```{r}
set.seed(1907)
fit <- stan_glm(log(weight) ~ height+factor(male)+ height:factor(male), data = data, refresh=0)

print(fit)
```

(ii) 

```{r}
p_male <- 1 - 0.52
pop1 <- data.frame(male = c(0, 1), N = c(1 - p_male, p_male))
pop2 <- NULL
cut <- c(0, seq(50, 80, 1), 999)
for (i in 1:(length(cut)-1)){
   # male height distribution in the population  
   m_h <- pnorm(cut[i + 1], 69.1, 2.9) -  pnorm(cut[i], 69.1, 2.9)
   # female height distribution 
   f_h <- pnorm(cut[i + 1], 63.7, 2.7) -  pnorm(cut[i], 63.7, 2.7)
   pop2 <- bind_rows(pop2, 
                     data.frame(height = cut[i], male = 1, N = m_h),
                     data.frame(height = cut[i], male = 0, N = f_h))
}

pop2$N <- ifelse(pop2$male == 1, p_male * pop2$N, (1 - p_male) * pop2$N) 
```

```{r}
pred2 <- exp(posterior_epred(fit, newdata = pop2))
```

(iii)

```{r}
poststrat2 <- pred2 %*% pop2$N 
median(poststrat2)
mad(poststrat2)
```



